name: CI-ML
# This will run integration tests against the ML package
on:
  push:
    branches:
      - main
    paths:
      - 'src/ml/**.py'

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run tests
        run: | 
          make test-ml


      


